name = str(input('dig. algo:'))
print('O tipo primitivo é:', type(name))
print('Só tem espaços??', name.isspace())
print('É um número??', name.isnumeric())
print('É alfabético??', name.isalnum())
print('É alfanúmerico??', name.isalnum())
print('Está em minúsculas??', name.islower())
print('Está em maiúsculas??', name.isupper())
print('É capitalizada??', name.istitle())
